messages:
  thermal-walk-rune:
    success: "&aHas aplicado con éxito esta runa a este objeto. &6Caminante de magma I&a."
    fail: "&cSólo puedes usar esta runa en un objeto."
    no-item: "&cDebes tirar el objeto en el que quieres usar esta runa."
  portable-nether-teleporter:
    nether-disabled: "&cThe Nether no está habilitado en este servidor"
    nether-world-not-set: "&cEl nombre actual del mundo inferior no está establecido en la configuración.,Por favor pida ayuda al administrador de su servidor"
    nether-world-not-found: "&cEl mundo inferior en configuración no existe."
    already-on-world: "&cActualmente estás en el Nether"
    cant-use-in-end: "&cNo puedes usar este artículo al final."
    teleporting: "&dTransmitiendo..."
    already-being-teleported: "&chas sido enviado"

default-nether-world: "world_nether"
travel-to-nether-from-end: false # If you wanna be able to use the Portable Nether Teleporter in the end
bed-rune-radius: 20
machines:
  piglin-attractor:
    radius: 32